// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/Volkov-D-A/docs-register-and-track/internal/models"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// AssignmentStore is an autogenerated mock type for the AssignmentStore type
type AssignmentStore struct {
	mock.Mock
	Effects []models.OutboxEvent
}

func (_m *AssignmentStore) UpdateDetailsWithOutbox(id, executorID uuid.UUID, content string, deadline *time.Time, coExecutorIDs []string, expectedUpdatedAt time.Time, effects []models.OutboxEvent) (*models.Assignment, error) {
	_m.Effects = append([]models.OutboxEvent(nil), effects...)
	ret := _m.Called(id, executorID, content, deadline, coExecutorIDs, expectedUpdatedAt, effects)
	if len(ret) == 0 {
		panic("no return value specified for UpdateDetailsWithOutbox")
	}
	var assignment *models.Assignment
	if ret.Get(0) != nil {
		assignment = ret.Get(0).(*models.Assignment)
	}
	return assignment, ret.Error(1)
}

func (_m *AssignmentStore) CreateWithOutbox(id uuid.UUID, documentID uuid.UUID, executorID uuid.UUID, content string, deadline *time.Time, coExecutorIDs []string, effects []models.OutboxEvent) (*models.Assignment, error) {
	_m.Effects = append([]models.OutboxEvent(nil), effects...)
	ret := _m.Called(id, documentID, executorID, content, deadline, coExecutorIDs, effects)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithOutbox")
	}

	var r0 *models.Assignment
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, uuid.UUID, string, *time.Time, []string, []models.OutboxEvent) (*models.Assignment, error)); ok {
		return rf(id, documentID, executorID, content, deadline, coExecutorIDs, effects)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, uuid.UUID, string, *time.Time, []string, []models.OutboxEvent) *models.Assignment); ok {
		r0 = rf(id, documentID, executorID, content, deadline, coExecutorIDs, effects)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Assignment)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID, uuid.UUID, string, *time.Time, []string, []models.OutboxEvent) error); ok {
		r1 = rf(id, documentID, executorID, content, deadline, coExecutorIDs, effects)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *AssignmentStore) DeleteWithOutbox(id uuid.UUID, effects []models.OutboxEvent) error {
	_m.Effects = append([]models.OutboxEvent(nil), effects...)
	ret := _m.Called(id, effects)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWithOutbox")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, []models.OutboxEvent) error); ok {
		r0 = rf(id, effects)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *AssignmentStore) GetByID(id uuid.UUID) (*models.Assignment, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Assignment
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Assignment, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Assignment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Assignment)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: filter
func (_m *AssignmentStore) GetList(filter models.AssignmentFilter) (*models.PagedResult[models.Assignment], error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 *models.PagedResult[models.Assignment]
	var r1 error
	if rf, ok := ret.Get(0).(func(models.AssignmentFilter) (*models.PagedResult[models.Assignment], error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(models.AssignmentFilter) *models.PagedResult[models.Assignment]); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PagedResult[models.Assignment])
		}
	}

	if rf, ok := ret.Get(1).(func(models.AssignmentFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasDocumentAccess provides a mock function with given fields: userID, documentID
func (_m *AssignmentStore) HasDocumentAccess(userID uuid.UUID, documentID uuid.UUID) (bool, error) {
	ret := _m.Called(userID, documentID)

	if len(ret) == 0 {
		panic("no return value specified for HasDocumentAccess")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(userID, documentID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(userID, documentID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(userID, documentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccessibleDocumentIDs provides a mock function with given fields: userID, documentIDs
func (_m *AssignmentStore) GetAccessibleDocumentIDs(userID uuid.UUID, documentIDs []uuid.UUID) (map[uuid.UUID]struct{}, error) {
	ret := _m.Called(userID, documentIDs)
	if len(ret) == 0 {
		panic("no return value specified for GetAccessibleDocumentIDs")
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, []uuid.UUID) (map[uuid.UUID]struct{}, error)); ok {
		return rf(userID, documentIDs)
	}
	var r0 map[uuid.UUID]struct{}
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(map[uuid.UUID]struct{})
	}
	return r0, ret.Error(1)
}

func (_m *AssignmentStore) UpdateWithOutbox(id uuid.UUID, executorID uuid.UUID, content string, deadline *time.Time, status string, report string, completedAt *time.Time, coExecutorIDs []string, effects []models.OutboxEvent) (*models.Assignment, error) {
	_m.Effects = append([]models.OutboxEvent(nil), effects...)
	ret := _m.Called(id, executorID, content, deadline, status, report, completedAt, coExecutorIDs, effects)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithOutbox")
	}

	var r0 *models.Assignment
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, string, *time.Time, string, string, *time.Time, []string, []models.OutboxEvent) (*models.Assignment, error)); ok {
		return rf(id, executorID, content, deadline, status, report, completedAt, coExecutorIDs, effects)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, string, *time.Time, string, string, *time.Time, []string, []models.OutboxEvent) *models.Assignment); ok {
		r0 = rf(id, executorID, content, deadline, status, report, completedAt, coExecutorIDs, effects)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Assignment)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID, string, *time.Time, string, string, *time.Time, []string, []models.OutboxEvent) error); ok {
		r1 = rf(id, executorID, content, deadline, status, report, completedAt, coExecutorIDs, effects)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAssignmentStore creates a new instance of AssignmentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssignmentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssignmentStore {
	mock := &AssignmentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
