// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "docflow/internal/models"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// AttachmentStore is an autogenerated mock type for the AttachmentStore type
type AttachmentStore struct {
	mock.Mock
}

// Create provides a mock function with given fields: a
func (_m *AttachmentStore) Create(a *models.Attachment) error {
	ret := _m.Called(a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Attachment) error); ok {
		r0 = rf(a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *AttachmentStore) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMultiple provides a mock function with given fields: ids
func (_m *AttachmentStore) DeleteMultiple(ids []uuid.UUID) error {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMultiple")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]uuid.UUID) error); ok {
		r0 = rf(ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByDocumentID provides a mock function with given fields: docID
func (_m *AttachmentStore) GetByDocumentID(docID uuid.UUID) ([]models.Attachment, error) {
	ret := _m.Called(docID)

	if len(ret) == 0 {
		panic("no return value specified for GetByDocumentID")
	}

	var r0 []models.Attachment
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]models.Attachment, error)); ok {
		return rf(docID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []models.Attachment); ok {
		r0 = rf(docID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Attachment)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(docID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *AttachmentStore) GetByID(id uuid.UUID) (*models.Attachment, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Attachment
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Attachment, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Attachment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Attachment)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOlderThan provides a mock function with given fields: date
func (_m *AttachmentStore) GetOlderThan(date time.Time) ([]models.Attachment, error) {
	ret := _m.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for GetOlderThan")
	}

	var r0 []models.Attachment
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time) ([]models.Attachment, error)); ok {
		return rf(date)
	}
	if rf, ok := ret.Get(0).(func(time.Time) []models.Attachment); ok {
		r0 = rf(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Attachment)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = rf(date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAttachmentStore creates a new instance of AttachmentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAttachmentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AttachmentStore {
	mock := &AttachmentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
