package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// FileStorage is an autogenerated mock type for the FileStorage type
type FileStorage struct {
	mock.Mock
}

// DeleteFile provides a mock function with given fields: ctx, objectName
func (_m *FileStorage) DeleteFile(ctx context.Context, objectName string) error {
	ret := _m.Called(ctx, objectName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, objectName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DownloadFile provides a mock function with given fields: ctx, objectName
func (_m *FileStorage) DownloadFile(ctx context.Context, objectName string, maxSize int64) ([]byte, error) {
	ret := _m.Called(ctx, objectName, maxSize)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFile")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, objectName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, objectName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, objectName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadFile provides a mock function with given fields: ctx, objectName, data, contentType
func (_m *FileStorage) UploadFile(ctx context.Context, objectName string, data io.Reader, size int64, contentType string) error {
	ret := _m.Called(ctx, objectName, data, size, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) error); ok {
		r0 = rf(ctx, objectName, data, size, contentType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

func (_m *FileStorage) DownloadFileToWriter(ctx context.Context, objectName string, writer io.Writer, maxSize int64) error {
	ret := _m.Called(ctx, objectName, writer, maxSize)
	if len(ret) == 0 {
		panic("no return value specified for DownloadFileToWriter")
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Writer, int64) error); ok {
		return rf(ctx, objectName, writer, maxSize)
	}
	return ret.Error(0)
}

// NewFileStorage creates a new instance of FileStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileStorage {
	mock := &FileStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
