// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "docflow/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// JournalStore is an autogenerated mock type for the JournalStore type
type JournalStore struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *JournalStore) Create(ctx context.Context, req models.CreateJournalEntryRequest) (uuid.UUID, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateJournalEntryRequest) (uuid.UUID, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateJournalEntryRequest) uuid.UUID); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateJournalEntryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByDocumentID provides a mock function with given fields: ctx, documentID, documentType
func (_m *JournalStore) GetByDocumentID(ctx context.Context, documentID uuid.UUID, documentType string) ([]models.JournalEntry, error) {
	ret := _m.Called(ctx, documentID, documentType)

	if len(ret) == 0 {
		panic("no return value specified for GetByDocumentID")
	}

	var r0 []models.JournalEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]models.JournalEntry, error)); ok {
		return rf(ctx, documentID, documentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []models.JournalEntry); ok {
		r0 = rf(ctx, documentID, documentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.JournalEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, documentID, documentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJournalStore creates a new instance of JournalStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJournalStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *JournalStore {
	mock := &JournalStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
