// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/Volkov-D-A/docs-register-and-track/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// NomenclatureStore is an autogenerated mock type for the NomenclatureStore type
type NomenclatureStore struct {
	mock.Mock
}

// Create provides a mock function with given fields: name, index, year, kindCode, separator, numberingMode
func (_m *NomenclatureStore) Create(name string, index string, year int, kindCode string, separator string, numberingMode string) (*models.Nomenclature, error) {
	ret := _m.Called(name, index, year, kindCode, separator, numberingMode)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Nomenclature
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int, string, string, string) (*models.Nomenclature, error)); ok {
		return rf(name, index, year, kindCode, separator, numberingMode)
	}
	if rf, ok := ret.Get(0).(func(string, string, int, string, string, string) *models.Nomenclature); ok {
		r0 = rf(name, index, year, kindCode, separator, numberingMode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Nomenclature)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int, string, string, string) error); ok {
		r1 = rf(name, index, year, kindCode, separator, numberingMode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *NomenclatureStore) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveByKind provides a mock function with given fields: kindCode, year
func (_m *NomenclatureStore) GetActiveByKind(kindCode string, year int) ([]models.Nomenclature, error) {
	ret := _m.Called(kindCode, year)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByKind")
	}

	var r0 []models.Nomenclature
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]models.Nomenclature, error)); ok {
		return rf(kindCode, year)
	}
	if rf, ok := ret.Get(0).(func(string, int) []models.Nomenclature); ok {
		r0 = rf(kindCode, year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Nomenclature)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(kindCode, year)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: year, kindCode
func (_m *NomenclatureStore) GetAll(year int, kindCode string) ([]models.Nomenclature, error) {
	ret := _m.Called(year, kindCode)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Nomenclature
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) ([]models.Nomenclature, error)); ok {
		return rf(year, kindCode)
	}
	if rf, ok := ret.Get(0).(func(int, string) []models.Nomenclature); ok {
		r0 = rf(year, kindCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Nomenclature)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(year, kindCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *NomenclatureStore) GetByID(id uuid.UUID) (*models.Nomenclature, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Nomenclature
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Nomenclature, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Nomenclature); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Nomenclature)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNextNumber provides a mock function with given fields: id
func (_m *NomenclatureStore) GetNextNumber(id uuid.UUID) (int, string, string, string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetNextNumber")
	}

	var r0 int
	var r1 string
	var r2 string
	var r3 string
	var r4 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (int, string, string, string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) int); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) string); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID) string); ok {
		r2 = rf(id)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(uuid.UUID) string); ok {
		r3 = rf(id)
	} else {
		r3 = ret.Get(3).(string)
	}

	if rf, ok := ret.Get(4).(func(uuid.UUID) error); ok {
		r4 = rf(id)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// Update provides a mock function with given fields: id, name, index, year, kindCode, separator, numberingMode, isActive
func (_m *NomenclatureStore) Update(id uuid.UUID, name string, index string, year int, kindCode string, separator string, numberingMode string, isActive bool) (*models.Nomenclature, error) {
	ret := _m.Called(id, name, index, year, kindCode, separator, numberingMode, isActive)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Nomenclature
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string, int, string, string, string, bool) (*models.Nomenclature, error)); ok {
		return rf(id, name, index, year, kindCode, separator, numberingMode, isActive)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string, int, string, string, string, bool) *models.Nomenclature); ok {
		r0 = rf(id, name, index, year, kindCode, separator, numberingMode, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Nomenclature)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string, string, int, string, string, string, bool) error); ok {
		r1 = rf(id, name, index, year, kindCode, separator, numberingMode, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNomenclatureStore creates a new instance of NomenclatureStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNomenclatureStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *NomenclatureStore {
	mock := &NomenclatureStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
