// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "docflow/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// SettingsStore is an autogenerated mock type for the SettingsStore type
type SettingsStore struct {
	mock.Mock
}

// Get provides a mock function with given fields: key
func (_m *SettingsStore) Get(key string) (*models.SystemSetting, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.SystemSetting
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.SystemSetting, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *models.SystemSetting); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SystemSetting)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with no fields
func (_m *SettingsStore) GetAll() ([]models.SystemSetting, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.SystemSetting
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.SystemSetting, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.SystemSetting); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SystemSetting)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: key, value
func (_m *SettingsStore) Update(key string, value string) error {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSettingsStore creates a new instance of SettingsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSettingsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *SettingsStore {
	mock := &SettingsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
