// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function Create(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<dto.Acknowledgment>;

export function Delete(arg1:string):Promise<void>;

export function GetAllActive():Promise<Array<dto.Acknowledgment>>;

export function GetList(arg1:string):Promise<Array<dto.Acknowledgment>>;

export function GetPendingForCurrentUser():Promise<Array<dto.Acknowledgment>>;

export function MarkConfirmed(arg1:string):Promise<void>;

export function MarkViewed(arg1:string):Promise<void>;
