// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2, arg3, arg4) {
  return window['go']['services']['AcknowledgmentService']['Create'](arg1, arg2, arg3, arg4);
}

export function Delete(arg1) {
  return window['go']['services']['AcknowledgmentService']['Delete'](arg1);
}

export function GetAllActive() {
  return window['go']['services']['AcknowledgmentService']['GetAllActive']();
}

export function GetList(arg1) {
  return window['go']['services']['AcknowledgmentService']['GetList'](arg1);
}

export function GetPendingForCurrentUser() {
  return window['go']['services']['AcknowledgmentService']['GetPendingForCurrentUser']();
}

export function MarkConfirmed(arg1) {
  return window['go']['services']['AcknowledgmentService']['MarkConfirmed'](arg1);
}

export function MarkViewed(arg1) {
  return window['go']['services']['AcknowledgmentService']['MarkViewed'](arg1);
}
