// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetAll(arg1:number,arg2:number):Promise<dto.AdminAuditLogPage>;
