// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function MarkAcknowledged(arg1:string):Promise<dto.AdministrativeOrderAcknowledgmentPerson>;
