// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {uuid} from '../models';

export function GetAll(arg1:number,arg2:number):Promise<dto.AdminAuditLogPage>;

export function LogAction(arg1:uuid.UUID,arg2:string,arg3:string,arg4:string):Promise<void>;
