// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['AssignmentService']['Create'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Delete(arg1) {
  return window['go']['services']['AssignmentService']['Delete'](arg1);
}

export function GetByID(arg1) {
  return window['go']['services']['AssignmentService']['GetByID'](arg1);
}

export function GetList(arg1) {
  return window['go']['services']['AssignmentService']['GetList'](arg1);
}

export function Update(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['AssignmentService']['Update'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateStatus(arg1, arg2, arg3) {
  return window['go']['services']['AssignmentService']['UpdateStatus'](arg1, arg2, arg3);
}
