// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {models} from '../models';
import {context} from '../models';

export function Create(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>):Promise<dto.Assignment>;

export function Delete(arg1:string):Promise<void>;

export function GetByID(arg1:string):Promise<dto.Assignment>;

export function GetList(arg1:models.AssignmentFilter):Promise<dto.PagedResult_docflow_internal_dto_Assignment_>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Update(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<dto.Assignment>;

export function UpdateStatus(arg1:string,arg2:string,arg3:string):Promise<dto.Assignment>;
