// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {dto} from '../models';
import {services} from '../models';
import {observability} from '../models';
import {context} from '../models';
import {io} from '../models';
import {uuid} from '../models';

export function AuthorizeDownload(arg1:string):Promise<models.Attachment>;

export function BulkDeleteOlderThan(arg1:string):Promise<number>;

export function Delete(arg1:string):Promise<void>;

export function DownloadToDisk(arg1:string):Promise<string>;

export function GetAssignmentFiles(arg1:string):Promise<Array<dto.Attachment>>;

export function GetList(arg1:string):Promise<Array<dto.Attachment>>;

export function MaxUploadSize():Promise<number>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function ReconcileStorage():Promise<models.AttachmentStorageReconciliation>;

export function SetAssignmentStore(arg1:services.AssignmentStore):Promise<void>;

export function SetOperationLifecycle(arg1:services.OperationLifecycle):Promise<void>;

export function SetOperationMetrics(arg1:observability.Registry):Promise<void>;

export function SetSubstitutionStore(arg1:services.UserSubstitutionStore):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StreamAttachment(arg1:context.Context,arg2:models.Attachment,arg3:io.Writer):Promise<void>;

export function Upload(arg1:string):Promise<Array<dto.Attachment>>;

export function UploadAssignmentContent(arg1:string,arg2:string,arg3:number,arg4:io.Reader):Promise<dto.Attachment>;

export function UploadContent(arg1:string,arg2:uuid.UUID,arg3:string,arg4:number,arg5:io.Reader):Promise<dto.Attachment>;

export function UploadForAssignment(arg1:string):Promise<Array<dto.Attachment>>;
