// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {dto} from '../models';
import {context} from '../models';

export function Delete(arg1:string):Promise<void>;

export function Download(arg1:string):Promise<models.DownloadResponse>;

export function DownloadToDisk(arg1:string):Promise<string>;

export function GetList(arg1:string):Promise<Array<dto.Attachment>>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Upload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<dto.Attachment>;
