// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {models} from '../models';

export function BulkDeleteOlderThan(arg1:string):Promise<number>;

export function Delete(arg1:string):Promise<void>;

export function DownloadToDisk(arg1:string):Promise<string>;

export function GetAssignmentFiles(arg1:string):Promise<Array<dto.Attachment>>;

export function GetList(arg1:string):Promise<Array<dto.Attachment>>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function ReconcileStorage():Promise<models.AttachmentStorageReconciliation>;

export function Upload(arg1:string):Promise<Array<dto.Attachment>>;

export function UploadForAssignment(arg1:string):Promise<Array<dto.Attachment>>;
