// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['services']['AttachmentService']['Delete'](arg1);
}

export function Download(arg1) {
  return window['go']['services']['AttachmentService']['Download'](arg1);
}

export function DownloadToDisk(arg1) {
  return window['go']['services']['AttachmentService']['DownloadToDisk'](arg1);
}

export function GetList(arg1) {
  return window['go']['services']['AttachmentService']['GetList'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['services']['AttachmentService']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['services']['AttachmentService']['OpenFolder'](arg1);
}

export function Upload(arg1, arg2, arg3, arg4) {
  return window['go']['services']['AttachmentService']['Upload'](arg1, arg2, arg3, arg4);
}
