// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function ChangePassword(arg1:string,arg2:string):Promise<void>;

export function GetCurrentUser():Promise<models.User>;

export function GetCurrentUserID():Promise<string>;

export function HasRole(arg1:string):Promise<boolean>;

export function IsAuthenticated():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<models.User>;

export function Logout():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
