// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1, arg2) {
  return window['go']['services']['AuthService']['ChangePassword'](arg1, arg2);
}

export function ChangeRequiredPassword(arg1, arg2, arg3) {
  return window['go']['services']['AuthService']['ChangeRequiredPassword'](arg1, arg2, arg3);
}

export function GetCurrentUser() {
  return window['go']['services']['AuthService']['GetCurrentUser']();
}

export function GetSessionState() {
  return window['go']['services']['AuthService']['GetSessionState']();
}

export function InitialSetup(arg1) {
  return window['go']['services']['AuthService']['InitialSetup'](arg1);
}

export function IsAuthenticated() {
  return window['go']['services']['AuthService']['IsAuthenticated']();
}

export function Login(arg1, arg2) {
  return window['go']['services']['AuthService']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['services']['AuthService']['Logout']();
}

export function NeedsInitialSetup() {
  return window['go']['services']['AuthService']['NeedsInitialSetup']();
}

export function UpdateProfile(arg1) {
  return window['go']['services']['AuthService']['UpdateProfile'](arg1);
}
