// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1, arg2) {
  return window['go']['services']['AuthService']['ChangePassword'](arg1, arg2);
}

export function GetActiveRole() {
  return window['go']['services']['AuthService']['GetActiveRole']();
}

export function GetCurrentAuditInfo() {
  return window['go']['services']['AuthService']['GetCurrentAuditInfo']();
}

export function GetCurrentUser() {
  return window['go']['services']['AuthService']['GetCurrentUser']();
}

export function GetCurrentUserID() {
  return window['go']['services']['AuthService']['GetCurrentUserID']();
}

export function GetCurrentUserUUID() {
  return window['go']['services']['AuthService']['GetCurrentUserUUID']();
}

export function HasActiveRole(arg1) {
  return window['go']['services']['AuthService']['HasActiveRole'](arg1);
}

export function HasRole(arg1) {
  return window['go']['services']['AuthService']['HasRole'](arg1);
}

export function InitialSetup(arg1) {
  return window['go']['services']['AuthService']['InitialSetup'](arg1);
}

export function IsAuthenticated() {
  return window['go']['services']['AuthService']['IsAuthenticated']();
}

export function Login(arg1, arg2) {
  return window['go']['services']['AuthService']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['services']['AuthService']['Logout']();
}

export function NeedsInitialSetup() {
  return window['go']['services']['AuthService']['NeedsInitialSetup']();
}

export function RequireActiveRole(arg1) {
  return window['go']['services']['AuthService']['RequireActiveRole'](arg1);
}

export function RequireAnyActiveRole(arg1) {
  return window['go']['services']['AuthService']['RequireAnyActiveRole'](arg1);
}

export function RequireAnyRole(arg1) {
  return window['go']['services']['AuthService']['RequireAnyRole'](arg1);
}

export function RequireRole(arg1) {
  return window['go']['services']['AuthService']['RequireRole'](arg1);
}

export function SetActiveRole(arg1) {
  return window['go']['services']['AuthService']['SetActiveRole'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['services']['AuthService']['UpdateProfile'](arg1);
}
