// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1, arg2) {
  return window['go']['services']['AuthService']['ChangePassword'](arg1, arg2);
}

export function GetCurrentUser() {
  return window['go']['services']['AuthService']['GetCurrentUser']();
}

export function GetCurrentUserID() {
  return window['go']['services']['AuthService']['GetCurrentUserID']();
}

export function HasRole(arg1) {
  return window['go']['services']['AuthService']['HasRole'](arg1);
}

export function IsAuthenticated() {
  return window['go']['services']['AuthService']['IsAuthenticated']();
}

export function Login(arg1, arg2) {
  return window['go']['services']['AuthService']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['services']['AuthService']['Logout']();
}

export function SetContext(arg1) {
  return window['go']['services']['AuthService']['SetContext'](arg1);
}
