// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {observability} from '../models';

export function GetActivity():Promise<dto.DashboardActivity>;

export function SetOperationMetrics(arg1:observability.Registry):Promise<void>;
