// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetStats(arg1:string,arg2:string,arg3:string):Promise<dto.DashboardStats>;
