// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStats() {
  return window['go']['services']['DashboardService']['GetStats']();
}

export function SetContext(arg1) {
  return window['go']['services']['DashboardService']['SetContext'](arg1);
}
