// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function GetStats(arg1:string,arg2:string):Promise<models.DashboardStats>;

export function SetContext(arg1:context.Context):Promise<void>;
