// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CreateDepartment(arg1:string,arg2:Array<string>):Promise<models.Department>;

export function DeleteDepartment(arg1:string):Promise<void>;

export function GetAllDepartments():Promise<Array<models.Department>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateDepartment(arg1:string,arg2:string,arg3:Array<string>):Promise<models.Department>;
