// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateDepartment(arg1:string,arg2:Array<string>):Promise<dto.Department>;

export function DeleteDepartment(arg1:string):Promise<void>;

export function GetAllDepartments():Promise<Array<dto.Department>>;

export function UpdateDepartment(arg1:string,arg2:string,arg3:Array<string>):Promise<dto.Department>;
