// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDepartment(arg1, arg2) {
  return window['go']['services']['DepartmentService']['CreateDepartment'](arg1, arg2);
}

export function DeleteDepartment(arg1) {
  return window['go']['services']['DepartmentService']['DeleteDepartment'](arg1);
}

export function GetAllDepartments() {
  return window['go']['services']['DepartmentService']['GetAllDepartments']();
}

export function SetContext(arg1) {
  return window['go']['services']['DepartmentService']['SetContext'](arg1);
}

export function UpdateDepartment(arg1, arg2, arg3) {
  return window['go']['services']['DepartmentService']['UpdateDepartment'](arg1, arg2, arg3);
}
