// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserAccessProfile(arg1) {
  return window['go']['services']['DocumentAccessAdminService']['GetUserAccessProfile'](arg1);
}

export function UpdateUserAccessProfile(arg1) {
  return window['go']['services']['DocumentAccessAdminService']['UpdateUserAccessProfile'](arg1);
}
