// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Register(arg1, arg2) {
  return window['go']['services']['DocumentRegistrationService']['Register'](arg1, arg2);
}

export function Update(arg1, arg2) {
  return window['go']['services']['DocumentRegistrationService']['Update'](arg1, arg2);
}
