// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentAccessSummary() {
  return window['go']['services']['DocumentKindService']['GetCurrentAccessSummary']();
}

export function SetServerClient(arg1) {
  return window['go']['services']['DocumentKindService']['SetServerClient'](arg1);
}
