// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetAll():Promise<Array<dto.DocumentKind>>;

export function GetAvailableForRegistration():Promise<Array<dto.DocumentKind>>;
