// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function Register(arg1:string,arg2:any):Promise<any>;

export function SetOperationLifecycle(arg1:services.OperationLifecycle):Promise<void>;

export function Update(arg1:string,arg2:any):Promise<any>;
