// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAll() {
  return window['go']['services']['DocumentKindService']['GetAll']();
}

export function GetAvailableForRegistration() {
  return window['go']['services']['DocumentKindService']['GetAvailableForRegistration']();
}
