// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {serverclient} from '../models';

export function GetCurrentAccessSummary():Promise<dto.CurrentAccessSummary>;

export function SetServerClient(arg1:serverclient.CurrentAccessClient):Promise<void>;
