// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetByID(arg1) {
  return window['go']['services']['DocumentQueryService']['GetByID'](arg1);
}

export function GetList(arg1, arg2) {
  return window['go']['services']['DocumentQueryService']['GetList'](arg1, arg2);
}
