// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {observability} from '../models';

export function CreateAdminDraft(arg1:string,arg2:services.AdminDraftCreateRequest):Promise<any>;

export function Register(arg1:string,arg2:any):Promise<any>;

export function SetOperationLifecycle(arg1:services.OperationLifecycle):Promise<void>;

export function SetOperationMetrics(arg1:observability.Registry):Promise<void>;

export function Update(arg1:string,arg2:any):Promise<any>;
