// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {serverclient} from '../models';

export function GetUserAccessProfile(arg1:string):Promise<models.UserDocumentAccessProfile>;

export function SetServerClient(arg1:serverclient.UserAccessClient):Promise<void>;

export function UpdateUserAccessProfile(arg1:models.UpdateUserDocumentAccessRequest):Promise<void>;
