// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetByID(arg1) {
  return window['go']['services']['IncomingDocumentService']['GetByID'](arg1);
}

export function GetCount() {
  return window['go']['services']['IncomingDocumentService']['GetCount']();
}

export function GetList(arg1) {
  return window['go']['services']['IncomingDocumentService']['GetList'](arg1);
}

export function Register(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) {
  return window['go']['services']['IncomingDocumentService']['Register'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
}

export function Update(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) {
  return window['go']['services']['IncomingDocumentService']['Update'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
}
