// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetByDocumentID(arg1) {
  return window['go']['services']['JournalService']['GetByDocumentID'](arg1);
}

export function LogAction(arg1, arg2) {
  return window['go']['services']['JournalService']['LogAction'](arg1, arg2);
}
