// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {services} from '../models';

export function GetByDocumentID(arg1:string):Promise<Array<dto.JournalEntry>>;

export function SetOperationLifecycle(arg1:services.OperationLifecycle):Promise<void>;
