// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';
import {models} from '../models';

export function GetByDocumentID(arg1:string):Promise<Array<dto.JournalEntry>>;

export function LogAction(arg1:context.Context,arg2:models.CreateJournalEntryRequest):Promise<void>;
