// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDocumentFlow(arg1) {
  return window['go']['services']['LinkService']['GetDocumentFlow'](arg1);
}

export function GetDocumentLinks(arg1) {
  return window['go']['services']['LinkService']['GetDocumentLinks'](arg1);
}

export function LinkDocuments(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['LinkService']['LinkDocuments'](arg1, arg2, arg3, arg4, arg5);
}

export function UnlinkDocument(arg1) {
  return window['go']['services']['LinkService']['UnlinkDocument'](arg1);
}
