// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {dto} from '../models';

export function GetDocumentFlow(arg1:string):Promise<services.GraphData>;

export function GetDocumentLinks(arg1:string):Promise<Array<dto.DocumentLink>>;

export function LinkDocuments(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<dto.DocumentLink>;

export function UnlinkDocument(arg1:string):Promise<void>;
