// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';
import {context} from '../models';

export function GetDocumentFlow(arg1:string):Promise<services.GraphData>;

export function GetDocumentLinks(arg1:string):Promise<Array<models.DocumentLink>>;

export function LinkDocuments(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.DocumentLink>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UnlinkDocument(arg1:string):Promise<void>;
