// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2, arg3, arg4) {
  return window['go']['services']['NomenclatureService']['Create'](...arguments);
}

export function Delete(arg1) {
  return window['go']['services']['NomenclatureService']['Delete'](arg1);
}

export function GetActiveForKind(arg1) {
  return window['go']['services']['NomenclatureService']['GetActiveForKind'](arg1);
}

export function GetAll(arg1, arg2) {
  return window['go']['services']['NomenclatureService']['GetAll'](arg1, arg2);
}

export function Update(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['NomenclatureService']['Update'](...arguments);
}
