// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function Create(arg1:string,arg2:string,arg3:number,arg4:string):Promise<dto.Nomenclature>;

export function Delete(arg1:string):Promise<void>;

export function GetActiveForDirection(arg1:string):Promise<Array<dto.Nomenclature>>;

export function GetAll(arg1:number,arg2:string):Promise<Array<dto.Nomenclature>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Update(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:boolean):Promise<dto.Nomenclature>;
