// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetFailed(arg1:number):Promise<Array<models.FailedOutboxEvent>>;

export function GetStats():Promise<models.OutboxStats>;

export function Requeue(arg1:string):Promise<void>;
