// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFailed(arg1) {
  return window['go']['services']['OutboxAdminService']['GetFailed'](arg1);
}

export function GetStats() {
  return window['go']['services']['OutboxAdminService']['GetStats']();
}

export function Requeue(arg1) {
  return window['go']['services']['OutboxAdminService']['Requeue'](arg1);
}
