// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {models} from '../models';

export function Delete(arg1:string):Promise<void>;

export function GetByID(arg1:string):Promise<dto.OutgoingDocument>;

export function GetCount():Promise<number>;

export function GetList(arg1:models.OutgoingDocumentFilter):Promise<dto.PagedResult_docflow_internal_dto_OutgoingDocument_>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:number,arg9:string,arg10:string):Promise<dto.OutgoingDocument>;

export function Update(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:number,arg9:string,arg10:string):Promise<dto.OutgoingDocument>;
