// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['services']['OutgoingDocumentService']['Delete'](arg1);
}

export function GetByID(arg1) {
  return window['go']['services']['OutgoingDocumentService']['GetByID'](arg1);
}

export function GetCount() {
  return window['go']['services']['OutgoingDocumentService']['GetCount']();
}

export function GetList(arg1) {
  return window['go']['services']['OutgoingDocumentService']['GetList'](arg1);
}

export function Register(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['services']['OutgoingDocumentService']['Register'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function SetContext(arg1) {
  return window['go']['services']['OutgoingDocumentService']['SetContext'](arg1);
}

export function Update(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['services']['OutgoingDocumentService']['Update'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}
