// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDocumentType(arg1) {
  return window['go']['services']['ReferenceService']['CreateDocumentType'](arg1);
}

export function DeleteDocumentType(arg1) {
  return window['go']['services']['ReferenceService']['DeleteDocumentType'](arg1);
}

export function DeleteOrganization(arg1) {
  return window['go']['services']['ReferenceService']['DeleteOrganization'](arg1);
}

export function FindOrCreateOrganization(arg1) {
  return window['go']['services']['ReferenceService']['FindOrCreateOrganization'](arg1);
}

export function GetDocumentTypes() {
  return window['go']['services']['ReferenceService']['GetDocumentTypes']();
}

export function GetOrganizations() {
  return window['go']['services']['ReferenceService']['GetOrganizations']();
}

export function SearchOrganizations(arg1) {
  return window['go']['services']['ReferenceService']['SearchOrganizations'](arg1);
}

export function UpdateDocumentType(arg1, arg2) {
  return window['go']['services']['ReferenceService']['UpdateDocumentType'](arg1, arg2);
}

export function UpdateOrganization(arg1, arg2) {
  return window['go']['services']['ReferenceService']['UpdateOrganization'](arg1, arg2);
}
