// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function CreateDocumentType(arg1:string):Promise<dto.DocumentType>;

export function DeleteDocumentType(arg1:string):Promise<void>;

export function DeleteOrganization(arg1:string):Promise<void>;

export function FindOrCreateOrganization(arg1:string):Promise<dto.Organization>;

export function GetDocumentTypes():Promise<Array<dto.DocumentType>>;

export function GetOrganizations():Promise<Array<dto.Organization>>;

export function SearchOrganizations(arg1:string):Promise<Array<dto.Organization>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateDocumentType(arg1:string,arg2:string):Promise<void>;

export function UpdateOrganization(arg1:string,arg2:string):Promise<void>;
