// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetCurrent():Promise<models.ReleaseNote>;

export function MarkCurrentViewed():Promise<void>;
