// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrent() {
  return window['go']['services']['ReleaseNoteService']['GetCurrent']();
}

export function MarkCurrentViewed() {
  return window['go']['services']['ReleaseNoteService']['MarkCurrentViewed']();
}
