// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Create(arg1:models.CreateReleaseNoteRequest):Promise<models.ReleaseNote>;

export function GetAll():Promise<Array<models.ReleaseNote>>;

export function GetCurrent():Promise<models.ReleaseNote>;

export function MarkCurrentViewed():Promise<void>;

export function MarkViewed(arg1:string):Promise<void>;

export function SetCurrent(arg1:string):Promise<void>;
