// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['services']['ReleaseNoteService']['Create'](arg1);
}

export function GetAll() {
  return window['go']['services']['ReleaseNoteService']['GetAll']();
}

export function GetCurrent() {
  return window['go']['services']['ReleaseNoteService']['GetCurrent']();
}

export function MarkCurrentViewed() {
  return window['go']['services']['ReleaseNoteService']['MarkCurrentViewed']();
}

export function MarkViewed(arg1) {
  return window['go']['services']['ReleaseNoteService']['MarkViewed'](arg1);
}

export function SetCurrent(arg1) {
  return window['go']['services']['ReleaseNoteService']['SetCurrent'](arg1);
}
