// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateSchedule(arg1:models.ReportScheduleRequest):Promise<models.ReportSchedule>;

export function DisableSchedule(arg1:string):Promise<void>;

export function DownloadRun(arg1:string):Promise<string>;

export function Export(arg1:models.ReportRequest,arg2:string):Promise<string>;

export function GetFilters():Promise<models.ReportFilters>;

export function ListRuns(arg1:string):Promise<Array<models.ReportRun>>;

export function ListSchedules():Promise<Array<models.ReportSchedule>>;

export function RetryRun(arg1:string):Promise<void>;

export function Run(arg1:models.ReportRequest):Promise<models.ReportResult>;
