// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSchedule(arg1) {
  return window['go']['services']['ReportingService']['CreateSchedule'](arg1);
}

export function DisableSchedule(arg1) {
  return window['go']['services']['ReportingService']['DisableSchedule'](arg1);
}

export function DownloadRun(arg1) {
  return window['go']['services']['ReportingService']['DownloadRun'](arg1);
}

export function Export(arg1, arg2) {
  return window['go']['services']['ReportingService']['Export'](arg1, arg2);
}

export function GetFilters() {
  return window['go']['services']['ReportingService']['GetFilters']();
}

export function ListRuns(arg1) {
  return window['go']['services']['ReportingService']['ListRuns'](arg1);
}

export function ListSchedules() {
  return window['go']['services']['ReportingService']['ListSchedules']();
}

export function RetryRun(arg1) {
  return window['go']['services']['ReportingService']['RetryRun'](arg1);
}

export function Run(arg1) {
  return window['go']['services']['ReportingService']['Run'](arg1);
}
