// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function GetAll():Promise<Array<models.SystemSetting>>;

export function GetAllowedFileTypes():Promise<Array<string>>;

export function GetMaxFileSize():Promise<number>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Update(arg1:string,arg2:string):Promise<void>;
