// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {dto} from '../models';

export function GetAll():Promise<Array<models.SystemSetting>>;

export function GetMigrationStatus():Promise<dto.MigrationStatus>;

export function GetOrganizationShortName():Promise<string>;

export function IsAssignmentCompletionAttachmentsEnabled():Promise<boolean>;

export function RollbackMigration(arg1:models.RollbackMigrationRequest):Promise<void>;

export function RunMigrations(arg1:string):Promise<void>;

export function Update(arg1:string,arg2:string):Promise<void>;
