// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelBackup(arg1) {
  return window['go']['services']['SettingsService']['CancelBackup'](arg1);
}

export function CheckBackupConnection() {
  return window['go']['services']['SettingsService']['CheckBackupConnection']();
}

export function GetAll() {
  return window['go']['services']['SettingsService']['GetAll']();
}

export function GetBackupSettings() {
  return window['go']['services']['SettingsService']['GetBackupSettings']();
}

export function GetMigrationStatus() {
  return window['go']['services']['SettingsService']['GetMigrationStatus']();
}

export function GetOrganizationShortName() {
  return window['go']['services']['SettingsService']['GetOrganizationShortName']();
}

export function IsAssignmentCompletionAttachmentsEnabled() {
  return window['go']['services']['SettingsService']['IsAssignmentCompletionAttachmentsEnabled']();
}

export function ListBackups() {
  return window['go']['services']['SettingsService']['ListBackups']();
}

export function RetryBackup(arg1) {
  return window['go']['services']['SettingsService']['RetryBackup'](arg1);
}

export function RollbackMigration(arg1) {
  return window['go']['services']['SettingsService']['RollbackMigration'](arg1);
}

export function RunMigrations(arg1) {
  return window['go']['services']['SettingsService']['RunMigrations'](arg1);
}

export function SaveBackupSettings(arg1) {
  return window['go']['services']['SettingsService']['SaveBackupSettings'](arg1);
}

export function StartBackup() {
  return window['go']['services']['SettingsService']['StartBackup']();
}

export function Update(arg1, arg2) {
  return window['go']['services']['SettingsService']['Update'](arg1, arg2);
}
