// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAll() {
  return window['go']['services']['SettingsService']['GetAll']();
}

export function GetAllowedFileTypes() {
  return window['go']['services']['SettingsService']['GetAllowedFileTypes']();
}

export function GetMaxFileSize() {
  return window['go']['services']['SettingsService']['GetMaxFileSize']();
}

export function SetContext(arg1) {
  return window['go']['services']['SettingsService']['SetContext'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['services']['SettingsService']['Update'](arg1, arg2);
}
