// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAssignmentFilterOptions() {
  return window['go']['services']['StatisticsService']['GetAssignmentFilterOptions']();
}

export function GetAssignmentReport(arg1, arg2, arg3, arg4) {
  return window['go']['services']['StatisticsService']['GetAssignmentReport'](arg1, arg2, arg3, arg4);
}

export function GetAssignmentStatistics() {
  return window['go']['services']['StatisticsService']['GetAssignmentStatistics']();
}

export function GetDocumentFilterOptions() {
  return window['go']['services']['StatisticsService']['GetDocumentFilterOptions']();
}

export function GetDocumentReport(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['StatisticsService']['GetDocumentReport'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetDocumentStatistics() {
  return window['go']['services']['StatisticsService']['GetDocumentStatistics']();
}

export function GetSystemStatistics() {
  return window['go']['services']['StatisticsService']['GetSystemStatistics']();
}
