// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAssignmentFilterOptions():Promise<models.AssignmentStatisticsFilters>;

export function GetAssignmentReport(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<models.AssignmentStatisticsReport>;

export function GetAssignmentStatistics():Promise<models.AssignmentStatistics>;

export function GetDocumentFilterOptions():Promise<models.DocumentStatisticsFilters>;

export function GetDocumentReport(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<models.DocumentStatisticsReport>;

export function GetDocumentStatistics():Promise<models.DocumentStatistics>;

export function GetSystemStatistics():Promise<models.SystemStatistics>;
