// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function GetBootstrapStatus():Promise<dto.BootstrapStatus>;

export function Startup(arg1:context.Context):Promise<void>;
