// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDBConnection() {
  return window['go']['services']['SystemService']['CheckDBConnection']();
}

export function ReconnectDB() {
  return window['go']['services']['SystemService']['ReconnectDB']();
}

export function Startup(arg1) {
  return window['go']['services']['SystemService']['Startup'](arg1);
}
