// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTheme() {
  return window['go']['services']['ThemeService']['GetTheme']();
}

export function SetTheme(arg1) {
  return window['go']['services']['ThemeService']['SetTheme'](arg1);
}
