// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTheme():Promise<string>;

export function SetTheme(arg1:string):Promise<void>;
