// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMySubstitution() {
  return window['go']['services']['UserSubstitutionService']['GetMySubstitution']();
}

export function GetUserSubstitution(arg1) {
  return window['go']['services']['UserSubstitutionService']['GetUserSubstitution'](arg1);
}

export function UpdateMySubstitution(arg1) {
  return window['go']['services']['UserSubstitutionService']['UpdateMySubstitution'](arg1);
}

export function UpdateUserSubstitution(arg1) {
  return window['go']['services']['UserSubstitutionService']['UpdateUserSubstitution'](arg1);
}
