// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CreateUser(arg1:models.CreateUserRequest):Promise<models.User>;

export function GetAllUsers():Promise<Array<models.User>>;

export function GetExecutors():Promise<Array<models.User>>;

export function ResetPassword(arg1:string,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateUser(arg1:models.UpdateUserRequest):Promise<models.User>;
