// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {dto} from '../models';

export function GetCurrentUserEvents(arg1:models.UserEventFilter):Promise<dto.PagedResult_github_com_Volkov_D_A_docs_register_and_track_internal_dto_UserEvent_>;

export function GetUnreadCount():Promise<number>;

export function MarkAllRead():Promise<void>;

export function MarkDocumentRead(arg1:string):Promise<void>;

export function MarkRead(arg1:string):Promise<void>;
