// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1) {
  return window['go']['services']['UserService']['CreateUser'](arg1);
}

export function GetAllUsers() {
  return window['go']['services']['UserService']['GetAllUsers']();
}

export function GetExecutors() {
  return window['go']['services']['UserService']['GetExecutors']();
}

export function ResetPassword(arg1, arg2) {
  return window['go']['services']['UserService']['ResetPassword'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['services']['UserService']['SetContext'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['services']['UserService']['UpdateUser'](arg1);
}
