// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentUserEvents(arg1) {
  return window['go']['services']['UserEventService']['GetCurrentUserEvents'](arg1);
}

export function GetUnreadCount() {
  return window['go']['services']['UserEventService']['GetUnreadCount']();
}

export function MarkAllRead() {
  return window['go']['services']['UserEventService']['MarkAllRead']();
}

export function MarkDocumentRead(arg1) {
  return window['go']['services']['UserEventService']['MarkDocumentRead'](arg1);
}

export function MarkRead(arg1) {
  return window['go']['services']['UserEventService']['MarkRead'](arg1);
}
