// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {dto} from '../models';
import {serverclient} from '../models';

export function CreateUser(arg1:models.CreateUserRequest):Promise<dto.User>;

export function GetAllUsers():Promise<Array<dto.User>>;

export function GetExecutors():Promise<Array<dto.User>>;

export function GetSubstitutionCandidates():Promise<Array<dto.User>>;

export function ResetPassword(arg1:string):Promise<string>;

export function SetServerClient(arg1:serverclient.UserClient):Promise<void>;

export function UpdateUser(arg1:models.UpdateUserRequest):Promise<dto.User>;
