// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {models} from '../models';

export function GetMySubstitution():Promise<dto.UserSubstitution>;

export function GetUserSubstitution(arg1:string):Promise<dto.UserSubstitution>;

export function UpdateMySubstitution(arg1:models.UpdateUserSubstitutionRequest):Promise<dto.UserSubstitution>;

export function UpdateUserSubstitution(arg1:models.UpdateUserSubstitutionRequest):Promise<dto.UserSubstitution>;
