// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOverview(arg1) {
  return window['go']['services']['WorkspaceService']['GetOverview'](arg1);
}

export function GetRecentDocuments() {
  return window['go']['services']['WorkspaceService']['GetRecentDocuments']();
}
