// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOverview(arg1, arg2) {
  return window['go']['services']['WorkspaceService']['GetOverview'](arg1, arg2);
}

export function GetRecentDocuments() {
  return window['go']['services']['WorkspaceService']['GetRecentDocuments']();
}

export function ListAcknowledgments(arg1, arg2, arg3) {
  return window['go']['services']['WorkspaceService']['ListAcknowledgments'](arg1, arg2, arg3);
}
