// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetOverview(arg1:string):Promise<dto.WorkspaceOverview>;

export function GetRecentDocuments():Promise<dto.WorkspaceDocuments>;
