[global]
    server role = standalone server
    server min protocol = SMB2_10
    server max protocol = SMB3
    server signing = mandatory
    smb encrypt = required
    map to guest = Never
    log level = 1
[backups]
    path = /shares/backups
    read only = no
    valid users = docflow
