// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/Volkov-D-A/docs-register-and-track/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AcknowledgmentStore is an autogenerated mock type for the AcknowledgmentStore type
type AcknowledgmentStore struct {
	mock.Mock
	Effects             []models.OutboxEvent
	ConfirmationEffects models.AcknowledgmentConfirmationEffects
}

func (_m *AcknowledgmentStore) CreateWithOutbox(a *models.Acknowledgment, effects []models.OutboxEvent) error {
	_m.Effects = append([]models.OutboxEvent(nil), effects...)
	ret := _m.Called(a, effects)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithOutbox")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Acknowledgment, []models.OutboxEvent) error); ok {
		r0 = rf(a, effects)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

func (_m *AcknowledgmentStore) DeleteWithOutbox(id uuid.UUID, effects []models.OutboxEvent) error {
	_m.Effects = append([]models.OutboxEvent(nil), effects...)
	ret := _m.Called(id, effects)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWithOutbox")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, []models.OutboxEvent) error); ok {
		r0 = rf(id, effects)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllActive provides a mock function with given fields: filter
func (_m *AcknowledgmentStore) GetAllActive(filter models.AcknowledgmentFilter) ([]models.Acknowledgment, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllActive")
	}

	var r0 []models.Acknowledgment
	var r1 error
	if rf, ok := ret.Get(0).(func(models.AcknowledgmentFilter) ([]models.Acknowledgment, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(models.AcknowledgmentFilter) []models.Acknowledgment); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Acknowledgment)
		}
	}

	if rf, ok := ret.Get(1).(func(models.AcknowledgmentFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByDocumentID provides a mock function with given fields: documentID
func (_m *AcknowledgmentStore) GetByDocumentID(documentID uuid.UUID) ([]models.Acknowledgment, error) {
	ret := _m.Called(documentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByDocumentID")
	}

	var r0 []models.Acknowledgment
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]models.Acknowledgment, error)); ok {
		return rf(documentID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []models.Acknowledgment); ok {
		r0 = rf(documentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Acknowledgment)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(documentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *AcknowledgmentStore) GetByID(id uuid.UUID) (*models.Acknowledgment, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Acknowledgment
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Acknowledgment, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Acknowledgment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Acknowledgment)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersByAcknowledgmentID provides a mock function with given fields: ackID
func (_m *AcknowledgmentStore) GetUsersByAcknowledgmentID(ackID uuid.UUID) ([]models.AcknowledgmentUser, error) {
	ret := _m.Called(ackID)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByAcknowledgmentID")
	}

	var r0 []models.AcknowledgmentUser
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]models.AcknowledgmentUser, error)); ok {
		return rf(ackID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []models.AcknowledgmentUser); ok {
		r0 = rf(ackID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.AcknowledgmentUser)
	}
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(ackID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasDocumentAccess provides a mock function with given fields: userID, documentID
func (_m *AcknowledgmentStore) HasDocumentAccess(userID uuid.UUID, documentID uuid.UUID) (bool, error) {
	ret := _m.Called(userID, documentID)

	if len(ret) == 0 {
		panic("no return value specified for HasDocumentAccess")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(userID, documentID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(userID, documentID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(userID, documentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccessibleDocumentIDs provides a mock function with given fields: userID, documentIDs
func (_m *AcknowledgmentStore) GetAccessibleDocumentIDs(userID uuid.UUID, documentIDs []uuid.UUID) (map[uuid.UUID]struct{}, error) {
	ret := _m.Called(userID, documentIDs)
	if len(ret) == 0 {
		panic("no return value specified for GetAccessibleDocumentIDs")
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, []uuid.UUID) (map[uuid.UUID]struct{}, error)); ok {
		return rf(userID, documentIDs)
	}
	var r0 map[uuid.UUID]struct{}
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(map[uuid.UUID]struct{})
	}
	return r0, ret.Error(1)
}

func (_m *AcknowledgmentStore) MarkConfirmedWithEffects(ackID uuid.UUID, userID uuid.UUID, effects models.AcknowledgmentConfirmationEffects) error {
	_m.ConfirmationEffects = effects
	ret := _m.Called(ackID, userID, effects)

	if len(ret) == 0 {
		panic("no return value specified for MarkConfirmedWithEffects")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, models.AcknowledgmentConfirmationEffects) error); ok {
		r0 = rf(ackID, userID, effects)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

func (_m *AcknowledgmentStore) MarkViewedWithOutbox(ackID uuid.UUID, userID uuid.UUID, effects []models.OutboxEvent) error {
	_m.Effects = append([]models.OutboxEvent(nil), effects...)
	ret := _m.Called(ackID, userID, effects)

	if len(ret) == 0 {
		panic("no return value specified for MarkViewedWithOutbox")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, []models.OutboxEvent) error); ok {
		r0 = rf(ackID, userID, effects)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAcknowledgmentStore creates a new instance of AcknowledgmentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAcknowledgmentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AcknowledgmentStore {
	mock := &AcknowledgmentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

func (_m *AcknowledgmentStore) GetPendingForUsers(ids []uuid.UUID) (map[uuid.UUID][]models.Acknowledgment, error) {
	ret := _m.Called(ids)
	if rf, ok := ret.Get(0).(func([]uuid.UUID) (map[uuid.UUID][]models.Acknowledgment, error)); ok {
		return rf(ids)
	}
	var result map[uuid.UUID][]models.Acknowledgment
	if ret.Get(0) != nil {
		result = ret.Get(0).(map[uuid.UUID][]models.Acknowledgment)
	}
	return result, ret.Error(1)
}
