// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/Volkov-D-A/docs-register-and-track/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// DashboardStore is an autogenerated mock type for the DashboardStore type
type DashboardStore struct {
	mock.Mock
}

// GetExpiringAssignments provides a mock function with given fields: filter
func (_m *DashboardStore) GetExpiringAssignments(filter models.DashboardAssignmentFilter) ([]models.Assignment, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiringAssignments")
	}

	var r0 []models.Assignment
	var r1 error
	if rf, ok := ret.Get(0).(func(models.DashboardAssignmentFilter) ([]models.Assignment, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(models.DashboardAssignmentFilter) []models.Assignment); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Assignment)
		}
	}

	if rf, ok := ret.Get(1).(func(models.DashboardAssignmentFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDashboardStore creates a new instance of DashboardStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDashboardStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *DashboardStore {
	mock := &DashboardStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
