// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/Volkov-D-A/docs-register-and-track/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// DepartmentStore is an autogenerated mock type for the DepartmentStore type
type DepartmentStore struct {
	mock.Mock
}

// GetAll provides a mock function with no fields
func (_m *DepartmentStore) GetAll() ([]models.Department, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Department
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Department, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Department); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Department)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNomenclatureIDs provides a mock function with given fields: departmentID
func (_m *DepartmentStore) GetNomenclatureIDs(departmentID uuid.UUID) ([]string, error) {
	ret := _m.Called(departmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetNomenclatureIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]string, error)); ok {
		return rf(departmentID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []string); ok {
		r0 = rf(departmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(departmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDepartmentStore creates a new instance of DepartmentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDepartmentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *DepartmentStore {
	mock := &DepartmentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
