// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/Volkov-D-A/docs-register-and-track/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IncomingDocStore is an autogenerated mock type for the IncomingDocStore type
type IncomingDocStore struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: id
func (_m *IncomingDocStore) GetByID(id uuid.UUID) (*models.IncomingDocument, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.IncomingDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.IncomingDocument, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.IncomingDocument); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.IncomingDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDs provides a mock function with given fields: ids
func (_m *IncomingDocStore) GetByIDs(ids []uuid.UUID) ([]models.IncomingDocument, error) {
	ret := _m.Called(ids)
	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}
	if rf, ok := ret.Get(0).(func([]uuid.UUID) ([]models.IncomingDocument, error)); ok {
		return rf(ids)
	}
	var r0 []models.IncomingDocument
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.IncomingDocument)
	}
	return r0, ret.Error(1)
}

// GetCount provides a mock function with no fields
func (_m *IncomingDocStore) GetCount() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: filter
func (_m *IncomingDocStore) GetList(filter models.DocumentFilter) (*models.PagedResult[models.IncomingDocument], error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 *models.PagedResult[models.IncomingDocument]
	var r1 error
	if rf, ok := ret.Get(0).(func(models.DocumentFilter) (*models.PagedResult[models.IncomingDocument], error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(models.DocumentFilter) *models.PagedResult[models.IncomingDocument]); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PagedResult[models.IncomingDocument])
		}
	}

	if rf, ok := ret.Get(1).(func(models.DocumentFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIncomingDocStore creates a new instance of IncomingDocStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIncomingDocStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *IncomingDocStore {
	mock := &IncomingDocStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
