// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/Volkov-D-A/docs-register-and-track/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// NomenclatureStore is an autogenerated mock type for the NomenclatureStore type
type NomenclatureStore struct {
	mock.Mock
}

// GetActiveByKind provides a mock function with given fields: kindCode, year
func (_m *NomenclatureStore) GetActiveByKind(kindCode string, year int) ([]models.Nomenclature, error) {
	ret := _m.Called(kindCode, year)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByKind")
	}

	var r0 []models.Nomenclature
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]models.Nomenclature, error)); ok {
		return rf(kindCode, year)
	}
	if rf, ok := ret.Get(0).(func(string, int) []models.Nomenclature); ok {
		r0 = rf(kindCode, year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Nomenclature)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(kindCode, year)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: year, kindCode
func (_m *NomenclatureStore) GetAll(year int, kindCode string) ([]models.Nomenclature, error) {
	ret := _m.Called(year, kindCode)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Nomenclature
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) ([]models.Nomenclature, error)); ok {
		return rf(year, kindCode)
	}
	if rf, ok := ret.Get(0).(func(int, string) []models.Nomenclature); ok {
		r0 = rf(year, kindCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Nomenclature)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(year, kindCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *NomenclatureStore) GetByID(id uuid.UUID) (*models.Nomenclature, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Nomenclature
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Nomenclature, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Nomenclature); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Nomenclature)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNomenclatureStore creates a new instance of NomenclatureStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNomenclatureStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *NomenclatureStore {
	mock := &NomenclatureStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
