// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/Volkov-D-A/docs-register-and-track/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// ReferenceStore is an autogenerated mock type for the ReferenceStore type
type ReferenceStore struct {
	mock.Mock
}

// FindOrCreateOrganization provides a mock function with given fields: name
func (_m *ReferenceStore) FindOrCreateOrganization(name string) (*models.Organization, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreateOrganization")
	}

	var r0 *models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Organization, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Organization); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllOrganizations provides a mock function with no fields
func (_m *ReferenceStore) GetAllOrganizations() ([]models.Organization, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllOrganizations")
	}

	var r0 []models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Organization, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Organization); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchOrganizations provides a mock function with given fields: query
func (_m *ReferenceStore) SearchOrganizations(query string) ([]models.Organization, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for SearchOrganizations")
	}

	var r0 []models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]models.Organization, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) []models.Organization); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOrCreateResolutionExecutor provides a mock function with given fields: name
func (_m *ReferenceStore) FindOrCreateResolutionExecutor(name string) (*models.ResolutionExecutor, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreateResolutionExecutor")
	}

	var r0 *models.ResolutionExecutor
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.ResolutionExecutor, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *models.ResolutionExecutor); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ResolutionExecutor)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllResolutionExecutors provides a mock function with no fields
func (_m *ReferenceStore) GetAllResolutionExecutors() ([]models.ResolutionExecutor, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllResolutionExecutors")
	}

	var r0 []models.ResolutionExecutor
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.ResolutionExecutor, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.ResolutionExecutor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ResolutionExecutor)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchResolutionExecutors provides a mock function with given fields: query
func (_m *ReferenceStore) SearchResolutionExecutors(query string) ([]models.ResolutionExecutor, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for SearchResolutionExecutors")
	}

	var r0 []models.ResolutionExecutor
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]models.ResolutionExecutor, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) []models.ResolutionExecutor); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ResolutionExecutor)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReferenceStore creates a new instance of ReferenceStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReferenceStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReferenceStore {
	mock := &ReferenceStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
